name: authenticator
description: "Authenticator App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: 3.6.0
  flutter: 3.27.1

dependencies:
  base32: ^2.1.3
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  logger: ^2.5.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  qr_code_scanner_plus: ^2.0.10+1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
