name: authenticator
description: "Authenticator App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1-alpha

environment:
  sdk: 3.6.0
  flutter: 3.27.1

dependencies:
  base32: ^2.0.4
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_zxing: ^1.7.0
  logger: ^2.4.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
