name: 'Authenticator Release CI'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: 'clone repository'
        uses: actions/checkout@v4

      - name: 'flutter get - test - build'
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: fluter/authenticator/pubspec.yaml

      - run: cd fluter/authenticator && flutter pub get
      
      - run: cd fluter/authenticator && flutter build apk --split-per-abi
      
      - name: "push artifacts to releases"
        uses: ncipollo/release-action@v1
        with: 
          artifacts: fluter/authenticator/build/app/outputs/apk/release/*.apk
          tag: v0.0.1-alpha
          token: ${{ secrets.RELEASE_TOKEN }}